### ISSUE TITLE
为什么用fis3还需要安装webpack

### ISSUE THREAD

**Issue by juanbaby2015** [okoala/vue-fis3#10]
npm install     安装依赖包报错，如下

tangjuandeMacBook-Pro:fis3-vue tangjuan$  npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated fis3-hook-module@1.2.2: please use fis3-hook-commonjs or fis3-hook-amd or fis3-hook-system instead
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated has-color@0.1.7: Renamed to supports-color. If you're using chalk, upgrade to the latest version. https://github.com/chalk/supports-color
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> fsevents@1.0.14 install /Users/tangjuan/fis3-vue/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/tangjuan/fis3-vue/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" is installed via remote

> node-sass@3.8.0 install /Users/tangjuan/fis3-vue/node_modules/node-sass
> node scripts/install.js

**Comment by okoala** [comment]
Webpack来处理node_modules里面的依赖，不过现在fis3可以处理了，确实可以去掉了
