### ISSUE TITLE
webpack 的依赖是用来干什么的？

### ISSUE THREAD

**Issue by e-cloud** [okoala/vue-fis3#3]
如题

**Comment by okoala** [comment]
@e-cloud  打包node_modules里面的依赖

**Comment by dsonet** [comment]
@okoala 现在已经有了 https://github.com/fex-team/fis3-hook-node_modules 这个支持 node_modules 的hook 了应该就可以去掉 webpack 的依赖了吧

**Comment by okoala** [comment]
@dsonet  好，我先看看~
